# Generated by Django 3.2.6 on 2021-08-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_seasonproxy_tvshowproxy_tvshowseasonproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonProxy',
        ),
    ]
