# Generated by Django 3.2.6 on 2021-10-15 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='activate',
            new_name='active',
        ),
    ]
